# Generated by Django 3.1.1 on 2020-09-12 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='description',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='works.description'),
        ),
        migrations.AlterField(
            model_name='works',
            name='tags',
            field=models.ManyToManyField(default=None, to='works.Tags'),
        ),
    ]
