# Generated by Django 3.1.1 on 2020-09-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200913_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='works',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='works.description'),
        ),
        migrations.RemoveField(
            model_name='works',
            name='prog_lang',
        ),
        migrations.AlterField(
            model_name='works',
            name='tags',
            field=models.ManyToManyField(to='works.Tags'),
        ),
        migrations.AddField(
            model_name='works',
            name='prog_lang',
            field=models.ManyToManyField(to='works.ProgLang'),
        ),
    ]
