# Generated by Django 3.1.1 on 2020-09-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200913_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='prog_lang',
            field=models.ManyToManyField(blank=True, to='works.ProgLang'),
        ),
        migrations.AlterField(
            model_name='works',
            name='tags',
            field=models.ManyToManyField(blank=True, to='works.Tags'),
        ),
    ]
