# Generated by Django 3.1.1 on 2020-09-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20200913_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='prog_lang',
            field=models.ManyToManyField(blank=True, related_name='workss_as_prog_lang', to='works.ProgLang'),
        ),
    ]
