# Generated by Django 3.1.1 on 2020-09-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20200913_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='prog_lang',
            field=models.ManyToManyField(blank=True, to='works.ProgLang'),
        ),
    ]
