# Generated by Django 3.1.1 on 2020-09-13 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20200913_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='prog_lang',
        ),
        migrations.AddField(
            model_name='works',
            name='prog_lang',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='works',
            name='tags',
        ),
        migrations.AddField(
            model_name='works',
            name='tags',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
