# Generated by Django 3.1.1 on 2020-09-13 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20200913_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='prog_langs'),
            preserve_default=False,
        ),
    ]
