# Generated by Django 3.1.1 on 2020-09-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_proglang_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proglang',
            name='logo',
            field=models.FileField(upload_to='prog_langs'),
        ),
    ]
