# Generated by Django 3.1.1 on 2020-09-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_auto_20200913_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
