# Generated by Django 3.1.1 on 2020-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_auto_20200919_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
