# Generated by Django 3.1.1 on 2020-09-22 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_auto_20200921_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='repository',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
