# Generated by Django 3.1.1 on 2020-09-26 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_auto_20200923_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('prog_lang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='works.proglang')),
                ('category', models.CharField(max_length=155)),
                ('content', models.TextField()),
            ],
        ),
    ]
