# Generated by Django 3.1.1 on 2020-10-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_auto_20200930_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
