# Generated by Django 3.1.1 on 2020-10-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0018_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
